framework:
  test: true
  secret: '%env(APP_SECRET)%'
  router:
    strict_requirements: ~
  form: ~
  csrf_protection: ~
  validation: { enable_annotations: true }
  default_locale: "%locale%"
  trusted_hosts: ~
  session:
    # handler_id set to null will use default session handler from php.ini
    handler_id: ~
    cookie_secure: auto
    cookie_samesite: lax
  fragments: ~
  http_method_override: true
  serializer: { enabled: true }
