framework:
  secret: '%env(APP_SECRET)%'
  csrf_protection: true
  http_method_override: true
  test: true

  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native
  serializer: { enabled: true }
